#!/usr/bin/bash

# check if balatro is installed with proton
file="$HOME/.steam/steam/steamapps/compatdata/2379780/pfx/drive_c/users/steamuser/AppData/Roaming/Balatro/"
lovely_file="$HOME/.steam/steam/steamapps/common/Balatro"


if [ ! -d "$file" ] || [ ! -d "$lovely_file" ]; then
    echo "balatro is not installed properly"
    exit
fi

mkdir -p "$file/Mods"
mkdir -p "$file/config"

# installing lovely
wget https://github.com/ethangreen-dev/lovely-injector/releases/download/v0.7.1/lovely-x86_64-pc-windows-msvc.zip
unzip lovely-x86_64-pc-windows-msvc.zip
cp ./version.dll "$lovely_file/"
rm -r lovely-x86_64-pc-windows-msvc.zip

# installing steammods
git clone https://github.com/Steamodded/smods?tab=readme-ov-file "$file/Mods/smod"

# installing handy
git clone https://github.com/SleepyG11/HandyBalatro.git "$file/Mods/handy"
cp -r Handy.jkr "$file/config/"
